### ISSUE TITLE
Add Support For Multiple Usernames and Passwords

### ISSUE THREAD

**Issue by brandonkboswell** [aptible/docker-kibana#24]
We would like to be able to support multiple usernames and password so that our entire development team doesn't have to login with one shared account.

**Comment by chasballew** [comment]
@UserNotFound just pointed out to me, this is already possible, just use a comma-separated list of usernames/passwords, each pair separated by a colon: https://github.com/aptible/docker-kibana/blob/master/bin/run-kibana.sh#L11

**Comment by brandonkboswell** [comment]
Awesome @chasballew!
